# NEURONIX Calamares Finished Module Configuration

# What to do after installation
# showShell: open a terminal
# showRestartButton: show restart button
# showUrl: open a URL
# teardown: what to execute on exit

showShell: false
showRestartButton: true
restartNow: false
dontChroot: true
