# NEURONIX Calamares Locale Module Configuration

# Locale settings
region: Asia
zone: Jakarta
localeGenPath: "/run/current-system/sw/share/i18n/SUPPORTED"
useSystemTimezone: true
adjustLiveTimezone: false
