# NEURONIX Calamares Locale Module Configuration

# Locale settings
localeGenPath: "/run/current-system/sw/share/i18n/SUPPORTED"
localeChars: "UTF-8"
useSystemTimezone: true
adjustLiveTimezone: false
