# NEURONIX Btrfs ZSTD:3 & 1.0 GiB ESP Partitioning Recipe
efiSystemPartition: "/boot"
efiSystemPartitionSize: 1024M

defaultFileSystemType: "btrfs"

# Btrfs subvolumes and mount options are declared in mount.conf.
userSwapChoices:
  - none
  - small
  - suspend
  - file
