"""
NEURONIX Imperative-to-Declarative Reverse Engine (neuronix distill)
Converts ephemeral package executions and user requests into verified,
pure-functional NixOS flake declarations with atomic rollback safety.
"""

import os
import sys
import re
import json
import subprocess
import shutil
import tempfile

USER_PACKAGES_MODULE_PATH = "/etc/nixos/modules/custom/user-packages.nix"
FALLBACK_REPO_MODULE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "../../../modules/custom/user-packages.nix"
)

def verify_package_in_nixpkgs(package_name):
    """Formally verifies if a package exists in pure nixpkgs closure."""
    if not package_name or not re.match(r"^[a-zA-Z0-9_\.\-]+$", package_name):
        return False, f"Invalid package name format: '{package_name}'"
    
    env = os.environ.copy()
    if os.path.exists("/nix/var/nix/daemon-socket/socket") or "NIX_REMOTE" in env:
        env.setdefault("NIX_REMOTE", "daemon")

    # 1. First probe against locked nixpkgs flake input if available
    flake_locations = ["/etc/nixos", os.path.abspath(os.path.join(os.path.dirname(__file__), "../../.."))]
    for floc in flake_locations:
        if os.path.isfile(os.path.join(floc, "flake.lock")) and shutil.which("nix"):
            try:
                eval_cmd = [
                    "nix", "eval", "--extra-experimental-features", "nix-command flakes",
                    f"{floc}#nixosConfigurations.neuronix-desktop.pkgs.{package_name}.name"
                ]
                res = subprocess.run(eval_cmd, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True, timeout=8, check=False)
                if res.returncode == 0:
                    return True, "Valid pure derivation in locked flake nixpkgs"
            except Exception:
                pass

    # 2. Probe via nixpkgs channel / instantiate
    cmd = ["nix-instantiate", "<nixpkgs>", "-A", package_name]
    try:
        res = subprocess.run(
            cmd,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
            timeout=10,
            check=False
        )
        if res.returncode == 0:
            return True, "Valid pure derivation in nixpkgs"
    except Exception:
        pass

    return False, f"Package '{package_name}' not found in current nixpkgs channel"


def resolve_target_file():
    """Locates the active declarative custom packages file."""
    if os.path.exists(USER_PACKAGES_MODULE_PATH) or os.path.isdir(os.path.dirname(USER_PACKAGES_MODULE_PATH)):
        return USER_PACKAGES_MODULE_PATH
    return FALLBACK_REPO_MODULE

def distill_packages(packages, dry_run=False, force=False):
    """Declaratively ingests packages into user-packages.nix with machine-managed safety boundary."""
    if not packages:
        return {"status": "error", "message": "No packages specified for distillation."}

    results = []
    valid_packages = []
    
    for pkg in packages:
        pkg_clean = pkg.strip()
        if not pkg_clean:
            continue
        is_valid, reason = verify_package_in_nixpkgs(pkg_clean)
        results.append({"package": pkg_clean, "valid": is_valid, "reason": reason})
        if is_valid:
            valid_packages.append(pkg_clean)

    if not valid_packages:
        return {
            "status": "failed",
            "message": "None of the specified packages could be verified in nixpkgs.",
            "details": results
        }

    target_file = resolve_target_file()
    target_dir = os.path.dirname(target_file)
    os.makedirs(target_dir, exist_ok=True)

    original_content = ""
    existing_packages = set()

    if os.path.exists(target_file):
        with open(target_file, "r") as f:
            original_content = f.read()
        
        # Enforce machine-managed safety boundary
        if original_content.strip() and "AUTO-GENERATED BY NEURONIX DISTILL" not in original_content and not force:
            return {
                "status": "error",
                "message": f"Target file '{target_file}' is human-managed (lacks '# AUTO-GENERATED BY NEURONIX DISTILL' boundary marker). "
                           f"Distillation aborted to prevent overwriting custom configuration. Pass force=True or --force to override.",
                "human_managed": True,
                "target_file": target_file
            }

        # Parse existing packages
        match = re.search(r"environment\.systemPackages\s*=\s*with\s+pkgs;\s*\[([^\]]+)\]", original_content, re.DOTALL)
        if match:
            for item in match.group(1).split():
                clean_item = item.strip().strip('"').strip("'")
                if clean_item and not clean_item.startswith("#"):
                    existing_packages.add(clean_item)

    new_to_add = [p for p in valid_packages if p not in existing_packages]
    if not new_to_add:
        return {
            "status": "noop",
            "message": f"All specified packages ({', '.join(valid_packages)}) are already declared in {target_file}.",
            "declared_packages": sorted(list(existing_packages))
        }

    all_pkgs = sorted(list(existing_packages.union(set(new_to_add))))
    formatted_pkgs = "\n".join([f"    {p}" for p in all_pkgs])
    new_content = f"""# ==============================================================================
# AUTO-GENERATED BY NEURONIX DISTILL - DO NOT EDIT MANUALLY
# Machine-managed by 'neuronix distill'. User packages are distilled here.
# Custom manual modules should be maintained in separate configuration files.
# ==============================================================================
{{ pkgs, ... }}:

{{
  environment.systemPackages = with pkgs; [
{formatted_pkgs}
  ];
}}
"""

    if dry_run:
        return {
            "status": "dry_run_success",
            "message": f"Verified {len(new_to_add)} packages ready for declarative distillation.",
            "target_file": target_file,
            "packages_to_add": new_to_add,
            "proposed_content": new_content
        }

    # Atomic file replacement: write to temp file in target dir -> parse -> fsync -> atomic replace
    tmp_target = tempfile.NamedTemporaryFile(dir=target_dir, prefix=".user-packages-", suffix=".tmp", delete=False)
    try:
        tmp_target.write(new_content.encode("utf-8"))
        tmp_target.flush()
        os.fsync(tmp_target.fileno())
        tmp_target.close()

        # Verify Nix syntax of modified file BEFORE replacing target!
        syntax_cmd = ["nix-instantiate", "--parse", tmp_target.name]
        syntax_res = subprocess.run(syntax_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
        if syntax_res.returncode != 0:
            if os.path.exists(tmp_target.name):
                os.unlink(tmp_target.name)
            return {
                "status": "error",
                "message": "Syntax validation failed on generated Nix configuration.",
                "error_detail": syntax_res.stderr.decode("utf-8", errors="ignore")
            }

        os.replace(tmp_target.name, target_file)
    except PermissionError:
        if os.path.exists(tmp_target.name):
            os.unlink(tmp_target.name)
        return {
            "status": "error",
            "message": f"Permission denied writing to {target_file}. Elevate privileges with sudo."
        }
    except Exception as e:
        if os.path.exists(tmp_target.name):
            os.unlink(tmp_target.name)
        return {
            "status": "error",
            "message": f"Failed to distill packages into {target_file}: {e}"
        }

    return {
        "status": "success",
        "message": f"Successfully distilled {len(new_to_add)} packages into declarative state.",
        "target_file": target_file,
        "packages_added": new_to_add,
        "total_packages": all_pkgs
    }

def verify_nixpkgs_attribute(pkg):
    ok, _ = verify_package_in_nixpkgs(pkg)
    return ok

distill_package = distill_packages

