#!/usr/bin/env bash
# ==============================================================================
# NEURONIX CLI Modular Command Handler
# Part of Phase 4 Distribution Architecture
# ==============================================================================
show_help() {
    print_banner
    echo -e "${BOLD}USAGE:${RESET}"
    echo -e "  ${CYAN}${PROGRAM_NAME}${RESET} <COMMAND> [OPTIONS]\n"
    echo -e "${BOLD}CORE COMMANDS:${RESET}"
    echo -e "  ${GREEN}state${RESET} [action]  Provable state engine (attestation, causality, diff, recovery)"
    echo -e "  ${GREEN}hyperion${RESET} [act]  Provable Adaptive Execution Architecture (HDS, proofs, posture)"
    echo -e "  ${GREEN}facter${RESET} [opts]    Query deterministic hardware intelligence and HardwareRoot"
    echo -e "  ${GREEN}topology${RESET} [opts]  Reconstruct universal system dependency graph and blast radius"
    echo -e "  ${GREEN}storage${RESET} [plan]   Declarative storage planner with 7-factor safety firewall"
    echo -e "  ${GREEN}secret${RESET} [status]  Capability-bound age secret status and RAM materialization"
    echo -e "  ${GREEN}boot${RESET} [status]    Measured boot PCR telemetry and 5-stage Boot Health Contract"
    echo -e "  ${GREEN}status${RESET}          Display system telemetry dashboard and storage health"
    echo -e "  ${GREEN}diet${RESET}            Reclaim storage, optimize store hardlinks, and issue TRIM"
    echo -e "  ${GREEN}check-update${RESET}    Check for available upstream releases and flake updates"
    echo -e "  ${GREEN}upgrade${RESET} [opt]   Perform atomic system upgrade (--staged / --switch)"
    echo -e "  ${GREEN}run${RESET} [flags]     Adaptive workload execution (Tiers 0-3) or ephemeral nix-shell"
    echo -e "  ${GREEN}dev${RESET} <stack>     Launch hermetic developer stack (python/rust/node/ai/go/web3)"
    echo -e "  ${GREEN}sandbox${RESET} [opts]  In-memory OS Micro-VM sandbox for testing system configs"
    echo -e "  ${GREEN}container${RESET} <url>  Zero-copy ephemeral development container in RAM (/dev/shm)"
    echo -e "  ${GREEN}try${RESET} [options]   (Alias) Simulate and test configuration in an isolated Micro-VM"
    echo -e "  ${GREEN}verify${RESET} <pkg>    Declarative build verification for package derivations"
    echo -e "  ${GREEN}shield${RESET}          Dashboard diagnosa memori, ZRAM & PSI Active Memory Shield"
    echo -e "  ${GREEN}generations${RESET}     Display chronological timeline of system generations"
    echo -e "  ${GREEN}battery${RESET} [val]   Configure laptop battery charging threshold (80% ceiling)"
    echo -e "  ${GREEN}center${RESET}          Luncurkan aplikasi grafis NEURONIX Control Center"
    echo -e "  ${GREEN}mcp${RESET}             Luncurkan server Model Context Protocol (JSON-RPC 2.0 over stdio)"
    echo -e "  ${GREEN}undo${RESET}            Roll back to preceding system generation atomically"
    echo -e "  ${GREEN}doctor${RESET}          Diagnosa sistem mendalam & buat laporan issue terformat Markdown"
    echo -e "  ${GREEN}verify-passport${RESET} Standalone offline verification of cryptographic release passport"
    echo -e "  ${GREEN}verify-release${RESET}  Offline verification of release passport and supply chain integrity"
    echo -e "  ${GREEN}graph${RESET} [trace]   Inspect, verify, and trace the authoritative 10-node Evidence Graph"
    echo -e "  ${GREEN}welcome${RESET}         Luncurkan panduan sambutan interaktif dan onboarding wizard"
    echo -e "  ${GREEN}quickstart${RESET}      Katalog aplikasi harian terkurasi 1-klik (Flatpak/Flathub)"
    echo -e "  ${GREEN}kernel${RESET} [flavor] Manajemen & peralihan profil kernel (default/zen/lts/latest/hardened)"
    echo -e "  ${GREEN}manual${RESET} [topic]  Display system-embedded technical manual and AI directives"
    echo -e "  ${GREEN}sentinel${RESET} [opt]  Autonomous boot assessment, zero-brick watchdog & recovery"
    echo -e "  ${GREEN}diff${RESET} [A] [B]    Generational forensic diff (closures, units, and security)"
    echo -e "  ${GREEN}distill${RESET} <pkgs>  Reverse-compile ephemeral packages into declarative flake"
    echo -e "  ${GREEN}tune${RESET} [profile]  Deterministic workload matrix (gaming/battery/audio-daw/balanced)"
    echo -e "  ${GREEN}mesh${RESET} [status]   Local P2P binary cache mesh and peer discovery via mDNS"
    echo -e "  ${GREEN}daemon${RESET} [opt]    Autonomous micro-Rust systems daemon and AST query engine"
    echo -e "  ${GREEN}ghost${RESET} [cmd]     Zero-trace disposable session in volatile RAM overlay"
    echo -e "  ${GREEN}branch${RESET} [opt]    Atomic Btrfs/Reflink project workspace time-travel branching"
    echo -e "  ${GREEN}ebpf${RESET} [opt]      Declarative eBPF LSM syscall container and policy status"
    echo -e "  ${GREEN}version${RESET}         Display version and architecture metadata"
    echo -e "  ${GREEN}help${RESET}            Display this usage guide\n"
    echo -e "${BOLD}EXAMPLES:${RESET}"
    echo -e "  ${DIM}# Check system and storage health${RESET}"
    echo -e "  ${PROGRAM_NAME} status\n"
    echo -e "  ${DIM}# Check and stage system updates without active session disruption${RESET}"
    echo -e "  ${PROGRAM_NAME} check-update"
    echo -e "  ${PROGRAM_NAME} upgrade --staged\n"
    echo -e "  ${DIM}# Reclaim storage and release blocks to host storage via TRIM${RESET}"
    echo -e "  ${PROGRAM_NAME} diet\n"
    echo -e "  ${DIM}# Coba aplikasi tanpa mengotori PC (misal: jq dan cowsay)${RESET}"
    echo -e "  ${PROGRAM_NAME} run jq cowsay\n"
    echo -e "  ${DIM}# Kembalikan konfigurasi jika ada kesalahan${RESET}"
    echo -e "  ${PROGRAM_NAME} undo\n"
}

