#!/usr/bin/env bash
# ==============================================================================
# NEURONIX OS: Declarative Flake-Generating Installer Engine
# Part of Phase 4 Distribution Architecture
# Translates Calamares GUI selections into a pristine, reproducible NixOS Flake.
# ==============================================================================
set -euo pipefail

TARGET_ROOT="${TARGET_ROOT:-/mnt}"
TARGET_USER="${TARGET_USER:-neuronix}"
TARGET_HOSTNAME="${TARGET_HOSTNAME:-neuronix-box}"
SELECTED_DESKTOP="${SELECTED_DESKTOP:-kde}"
DRY_RUN="${DRY_RUN:-0}"

log() {
  echo -e "\033[1;32m[NEURONIX-INSTALLER]\033[0m $*"
}

log_warn() {
  echo -e "\033[1;33m[NEURONIX-INSTALLER WARN]\033[0m $*"
}

log_err() {
  echo -e "\033[1;31m[NEURONIX-INSTALLER ERROR]\033[0m $*" >&2
}

# Strict Input Validation (Privileged Sanitization Gatekeeper)
if ! [[ "$TARGET_USER" =~ ^[a-z_][a-z0-9_-]{0,31}$ ]]; then
  log_err "Invalid TARGET_USER: '${TARGET_USER}'. Must conform to POSIX username format (^[a-z_][a-z0-9_-]{0,31}$)."
  exit 1
fi

if ! [[ "$TARGET_HOSTNAME" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$ ]]; then
  log_err "Invalid TARGET_HOSTNAME: '${TARGET_HOSTNAME}'. Must conform to RFC 1123 hostname specification."
  exit 1
fi

case "$SELECTED_DESKTOP" in
  kde|gnome|hyprland) ;;
  *)
    log_err "Invalid SELECTED_DESKTOP: '${SELECTED_DESKTOP}'. Allowed values: kde, gnome, hyprland."
    exit 1
    ;;
esac

log "Starting NEURONIX declarative installation to target: $TARGET_ROOT"
log "Parameters: User=$TARGET_USER, Host=$TARGET_HOSTNAME, Desktop=$SELECTED_DESKTOP"

if [ "$DRY_RUN" -eq 1 ]; then
  log "Dry-run simulation mode active. Skipping physical partition creation."
  if [ "$TARGET_ROOT" = "/mnt" ]; then
    TARGET_ROOT="/tmp/neuronix-mock-install"
  fi
  rm -rf "$TARGET_ROOT"
  mkdir -p "$TARGET_ROOT/etc/nixos"
  if [ "$TARGET_ROOT" != "/tmp/neuronix-mock-install" ]; then
    rm -rf "/tmp/neuronix-mock-install"
    ln -sfn "$TARGET_ROOT" "/tmp/neuronix-mock-install"
  fi
fi

CONFIG_DIR="$TARGET_ROOT/etc/nixos"
mkdir -p "$CONFIG_DIR"

log "Generating hardware-configuration.nix autonomously..."
if [ "$DRY_RUN" -eq 0 ] && command -v nixos-generate-config >/dev/null 2>&1; then
  nixos-generate-config --root "$TARGET_ROOT"
else
  # Mock hardware config for dry-run or verification
  cat <<'HW_EOF' > "$CONFIG_DIR/hardware-configuration.nix"
# Generic hardware configuration generated by NEURONIX Installer Engine
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "kvm-amd" ];
  boot.extraModulePackages = [ ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
HW_EOF
fi

# Resolve versioning and platform architecture dynamically
VERSION_NIX="$(dirname "$(readlink -f "$0")")/../../version.nix"
NRX_VER="1.0.3"
NRX_RELEASE_TAG="v1.0.3"
NRX_STATE="24.11"
NRX_CHANNEL_STABLE="nixos-26.05"
NRX_CHANNEL_DEV="nixos-unstable"
NRX_CHANNEL="nixos-26.05"
NRX_COMMIT="577972710ddbf3f000ae7f184dd26c25264d7be7"

if [[ -f "$VERSION_NIX" ]]; then
  NRX_VER=$(grep -E 'version\s*=' "$VERSION_NIX" | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/')
  NRX_RELEASE_TAG=$(grep -E 'releaseTag\s*=' "$VERSION_NIX" | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/' || echo "v1.0.3")
  NRX_STATE=$(grep -E 'stateVersion\s*=' "$VERSION_NIX" | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/')
  NRX_CHANNEL_DEV=$(grep -E 'channelDevelopment\s*=' "$VERSION_NIX" | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/' || echo "nixos-unstable")
  NRX_CHANNEL_STABLE=$(grep -E 'channelStable\s*=' "$VERSION_NIX" | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/' || echo "nixos-26.05")
  if [[ "${NEURONIX_TRACK:-stable}" == "edge" ]]; then
    NRX_CHANNEL="$NRX_CHANNEL_DEV"
  else
    NRX_CHANNEL="$NRX_CHANNEL_STABLE"
  fi
  NRX_COMMIT=$(grep -E 'nixpkgsCommit\s*=' "$VERSION_NIX" | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/' || echo "577972710ddbf3f000ae7f184dd26c25264d7be7")
fi

TARGET_ARCH="${TARGET_ARCH:-$(uname -m)}"
case "$TARGET_ARCH" in
  x86_64) NIX_ARCH="x86_64-linux" ;;
  aarch64|arm64) NIX_ARCH="aarch64-linux" ;;
  *) NIX_ARCH="x86_64-linux" ;;
esac

log "Generating pure flake.nix configuration for target system ($NIX_ARCH)..."
cat <<FLAKE_EOF > "$CONFIG_DIR/flake.nix"
# ==============================================================================
# NEURONIX OS: Declarative Host Configuration
# Generated autonomously by NEURONIX Installer Engine ($NRX_VER)
# ==============================================================================
{
  description = "NEURONIX Host Configuration for $TARGET_HOSTNAME";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/$NRX_CHANNEL";
  };

  outputs = { self, nixpkgs, ... }@inputs: {
    nixosConfigurations."$TARGET_HOSTNAME" = nixpkgs.lib.nixosSystem {
      system = "$NIX_ARCH";
      modules = [
        ./hardware-configuration.nix
        ./configuration.nix
      ];
    };
  };
}
FLAKE_EOF

log "Generating curated configuration.nix..."
cat <<CONF_EOF > "$CONFIG_DIR/configuration.nix"
# ==============================================================================
# NEURONIX OS: Primary System Specification
# ==============================================================================
{ config, pkgs, lib, ... }:

{
  networking.hostName = "$TARGET_HOSTNAME";
  networking.networkmanager.enable = true;

  # Enable Flakes & modern Nix CLI
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nix.settings.auto-optimise-store = true;

  # Unfree package licensing (Steam, NVIDIA, Spotify)
  nixpkgs.config.allowUnfree = true;

  # Global nix-ld activation (Direct execution of Linux FHS binaries)
  programs.nix-ld.enable = true;

  # Bootloader systemd-boot with 15 generation threshold on 1.0 GiB ESP
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 15;
  boot.loader.efi.canTouchEfiVariables = true;
  time.hardwareClockInLocalTime = true;

  # Active Memory Pressure Shield (ZRAM ZSTD + systemd-oomd)
  zramSwap.enable = true;
  zramSwap.algorithm = "zstd";
  systemd.oomd.enable = true;
  boot.kernel.sysctl."vm.max_map_count" = 2147483642;
  boot.kernel.sysctl."vm.swappiness" = 180;

  # Audio PipeWire HD Duplex subsystem
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
  };

  # Flatpak & Flathub application marketplace
  services.flatpak.enable = true;

  # Btrfs Storage Maintenance & Auto-TRIM
  services.fstrim.enable = true;

  # Desktop Environment: $SELECTED_DESKTOP
CONF_EOF

if [ "$SELECTED_DESKTOP" == "kde" ]; then
  cat <<'DESK_EOF' >> "$CONFIG_DIR/configuration.nix"
  services.displayManager.sddm.enable = true;
  services.displayManager.sddm.wayland.enable = true;
  services.desktopManager.plasma6.enable = true;
DESK_EOF
elif [ "$SELECTED_DESKTOP" == "gnome" ]; then
  cat <<'DESK_EOF' >> "$CONFIG_DIR/configuration.nix"
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;
DESK_EOF
elif [ "$SELECTED_DESKTOP" == "hyprland" ]; then
  cat <<'DESK_EOF' >> "$CONFIG_DIR/configuration.nix"
  services.displayManager.sddm.enable = true;
  services.displayManager.sddm.wayland.enable = true;
  programs.hyprland.enable = true;
  programs.hyprland.xwayland.enable = true;
DESK_EOF
fi

cat <<USER_EOF >> "$CONFIG_DIR/configuration.nix"

  # System user account
  users.users.$TARGET_USER = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" "audio" ];
    description = "$TARGET_USER (NEURONIX)";
  };

  # Autonomous AI System Copilot (OpenCode)
  # Pre-installed by default across KDE, GNOME, and Hyprland.
  # To disable or remove: set enable = false; or toggle via NEURONIX Center.
  neuronix.services.opencode = {
    enable = true;
    autoUpdate.enable = true;
  };

  # Autonomous Update Notifier & Storage Diet Policy
  # Default: Desktop notification + 1-Click staged upgrade.
  # Auto-diet prunes generations older than 14 days and issues host SSD TRIM.
  neuronix.services.updates = {
    enable = true;
    enableNotifier = true;
    checkInterval = "daily";
    autoUpgrade = false;
    staged = true;
  };

  # Ephemeral & Storage Hygiene (Journal Ceiling & Boot /tmp Clean)
  boot.tmp.cleanOnBoot = true;

  system.stateVersion = "24.11";
}
USER_EOF

# Generate Release Manifest for System Traceability
MANIFEST_DIR="$TARGET_ROOT/etc/neuronix"
mkdir -p "$MANIFEST_DIR"
cat <<MANIFEST_EOF > "$MANIFEST_DIR/release.json"
{
  "distribution": "NEURONIX OS",
  "version": "$NRX_VER",
  "release_tag": "$NRX_RELEASE_TAG",
  "system": "$NIX_ARCH",
  "target_user": "$TARGET_USER",
  "target_hostname": "$TARGET_HOSTNAME",
  "desktop_environment": "$SELECTED_DESKTOP",
  "ai_agent": "opencode",
  "ai_agent_autoupdate": "daily",
  "update_notifier": "enabled",
  "storage_diet": "autonomous_14d",
  "storage_hygiene": "journal_tmp_flatpak",
  "nixpkgs_channel": "$NRX_CHANNEL",
  "nixpkgs_commit": "$NRX_COMMIT",
  "state_version": "$NRX_STATE",
  "installed_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
MANIFEST_EOF

log "✓ Declarative configuration and release manifest at $CONFIG_DIR generated successfully."

if [ "$DRY_RUN" -eq 0 ]; then
  log "Executing hermetic installation via nixos-install..."
  nixos-install --flake "$CONFIG_DIR#$TARGET_HOSTNAME" --no-root-passwd
  log "✓ System installation completed successfully!"
else
  log "✓ Dry-run verification successful! Configuration files are valid and hermetic."
fi
