# NEURONIX Calamares Installer Configuration
modules-search: [ local ]

instances:
  - id:       neuronix-engine
    module:   shellprocess
    config:   shellprocess-neuronix.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - shellprocess@neuronix-engine
  - show:
      - finished

branding: neuronix
prompt-install: true
dont-chroot: true
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
