# NEURONIX Btrfs ZSTD:3 & 1.0 GiB ESP Partitioning Recipe
efiSystemPartition: "/boot"
efiSystemPartitionSize: 1024M

defaultFileSystemType: "btrfs"

btrfsSubvolumes:
  - mountPoint: "/"
    subvolume: "@"
    options: "compress=zstd:3,noatime,space_cache=v2"
  - mountPoint: "/nix"
    subvolume: "@nix"
    options: "compress=zstd:3,noatime,space_cache=v2"
  - mountPoint: "/home"
    subvolume: "@home"
    options: "compress=zstd:3,noatime"
  - mountPoint: "/.snapshots"
    subvolume: "@snapshots"
    options: "compress=zstd:3,noatime"
  - mountPoint: "/swap"
    subvolume: "@swap"
    options: "nodatacow,noatime"

userSwapChoices:
  - none
  - small
  - suspend
  - file
