{ pkgs, lib, config, ... }:

# ==============================================================================
# NEURONIX OS: Declarative Secure Boot Subsystem (Lanzaboote Integration)
# Provides signed EFI binaries, kernel signing, and TPM2 measured boot.
#
# Status: EXPERIMENTAL (Hardware-dependent, requires UEFI MOK enrollment)
# Prerequisites:
#   1. UEFI Secure Boot set to Setup Mode in firmware settings.
#   2. Machine Owner Keys (MOK) generated via sbctl.
#   3. Lanzaboote flake input integrated into nixosConfiguration.
# ==============================================================================
{
  options = {
    neuronix.security.secureboot = {
      enable = lib.mkEnableOption "Lanzaboote-based UEFI Secure Boot signed chain";
      pkiBundle = lib.mkOption {
        type = lib.types.str;
        default = "/etc/secureboot";
        description = "Path to custom Secure Boot keys and PKI certificates generated by sbctl.";
      };
    };
  };

  config = lib.mkIf config.neuronix.security.secureboot.enable {
    # Systemd-boot is disabled when Lanzaboote replaces the default EFI loader
    boot.loader.systemd-boot.enable = lib.mkForce false;

    # Note: When Lanzaboote input is active in host flake, enable:
    # boot.lanzaboote = {
    #   enable = true;
    #   pkiBundle = config.neuronix.security.secureboot.pkiBundle;
    # };

    environment.systemPackages = with pkgs; [
      sbctl
      tpm2-tools
      efibootmgr
    ];
  };
}
